name = "weft-chals"
defaultTargets = ["WeftChals", "Tests"]

[leanOptions]
autoImplicit = false

[[require]]
name = "weft"
path = "../weft"

[[lean_lib]]
name = "WeftChals"

[[lean_lib]]
name = "Tests"
