name = "weft-chals"
defaultTargets = ["WeftChals", "Tests"]

[leanOptions]
autoImplicit = false

[[require]]
name = "weft"
path = "../weft"

[[require]]
name = "Wychelean"
git = "https://github.com/rozbb/wychelean"
rev = "51ff5d1855c53be8e6f60b9f4b8a9b835e357c0d"

[[require]]
name = "mathlib"
scope = "leanprover-community"
git = "https://github.com/leanprover-community/mathlib4"
rev = "633b366493a76df88a2bff099ed0cbf711a59ec9"

[[lean_lib]]
name = "WeftChals"

[[lean_lib]]
name = "Tests"
